Run puppeteer in headless mode
This allows epaper.js to run on fully headless devices without the need to set up a virtual frame buffer.

Those devices experience this error:
Error: Failed to launch the browser process!
(zenity:1375): Gtk-WARNING **: 17:30:07.547: cannot open display: